### ISSUE TITLE
Windows naming conflict

### ISSUE THREAD

**Issue by 1nfdev** [keys-pub/keysd#11] opened 2020-05-04 14:57 UTC
Windows support legacy DOS command `keys`.

I didn't install keys for CLI, so I don't know what will happen if install.
Just keep that in mind. Perhaps it may confuse or complicate writing cross-platform scripts.

I didn't find information on the DOS command `keys` on the Internet. I got the information from a message in the console, through `keys /?`, After the message `keys` -> "Keys mode is disabled."

**Comment by gabriel** [comment] 2020-05-27 19:02
Dupe of https://github.com/keys-pub/keys/issues/18

**Closed by gabriel** 2020-05-27 19:02 UTC
